module.exports = [
  require('./text'),
  require('./attr'),
  require('./each'),
  require('./if'),
  require('./prop'),
  require('./on'),
  require('./inner-html'),
  require('./inner-text'),
  require('./prevent'),
  require('./id'),
  require('./cloak'),
  require('./show'),
  require('./model-input'),
  require('./model-select'),
  require('./model-radio'),
  require('./model-checkbox'),
  require('./model-editable')
];